language: c

# Makes Travis clone the full repo so that the conda package can get the
# correct string from git describe and correctly label the package
git:
  depth: false

dist: bionic

env:
  global:
    - MINICONDA_DIR=$HOME/miniconda

before_script:
  # download miniconda
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $MINICONDA_DIR
  - source $MINICONDA_DIR/bin/activate $MINICONDA_DIR
  - conda config --set always_yes yes
  - conda config --set anaconda_upload yes
  - conda install anaconda conda-build


jobs:
  include:
    - stage: build
      name: Build
      if: branch != master
      script:
        - conda build ./conda

    - stage: build and deploy
      name: Build and Deploy
      if: branch = master
      script:
        - conda build ./conda --user $UPLOAD_USER --token $ANACONDA_API_TOKEN
